# Generated by Django 3.0.2 on 2020-02-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_code', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_display_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Product Catalog',
                'verbose_name_plural': 'Product Catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(default='123456', max_length=15)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
                'managed': True,
            },
        ),
    ]
