# Generated by Django 3.0.2 on 2020-02-03 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_to_customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributer_id', models.IntegerField(max_length=20)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 35, 22, 531795, tzinfo=utc), null=True)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 35, 22, 531826, tzinfo=utc), null=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 35, 22, 531846, tzinfo=utc), null=True)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 35, 22, 531862, tzinfo=utc), null=True)),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale_to_customers_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_code', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 35, 22, 532365, tzinfo=utc), null=True)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 35, 22, 532389, tzinfo=utc), null=True)),
                ('sales_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Sale_to_customers')),
            ],
            options={
                'verbose_name': 'Sales Detail',
                'verbose_name_plural': 'Sales Detail',
                'managed': True,
            },
        ),
    ]
