# Generated by Django 3.0.2 on 2020-02-03 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200203_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_to_customers',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 36, 50, 215779, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 36, 50, 215796, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 36, 50, 215760, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 36, 50, 215730, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers_detail',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 36, 50, 216302, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers_detail',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 9, 36, 50, 216325, tzinfo=utc), null=True),
        ),
    ]
