# Generated by Django 3.0.2 on 2020-02-03 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200203_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_to_customers',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='uploadimages/'),
        ),
        migrations.AddField(
            model_name='sale_to_customers',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 10, 41, 24, 3355, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 10, 41, 24, 3384, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers_detail',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 10, 41, 24, 4108, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers_detail',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 3, 10, 41, 24, 4132, tzinfo=utc), null=True),
        ),
    ]
