# Generated by Django 3.0.2 on 2020-02-06 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200203_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_to_customers',
            name='buyer_distributer_id',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 6, 7, 31, 0, 487447, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 6, 7, 31, 0, 487473, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers_detail',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 6, 7, 31, 0, 488163, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers_detail',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 6, 7, 31, 0, 488187, tzinfo=utc), null=True),
        ),
    ]
