# Generated by Django 3.0.2 on 2020-02-06 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20200206_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_to_customers',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 6, 7, 32, 35, 43279, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 6, 7, 32, 35, 43304, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers_detail',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 6, 7, 32, 35, 44031, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_customers_detail',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 6, 7, 32, 35, 44055, tzinfo=utc), null=True),
        ),
    ]
